import { SiteSettings } from '@/types/settings';

export const fallbackSettings: SiteSettings = {
  siteName: 'Ankesh Kumar',
  logoText: 'Ankesh',
  tagline: 'I build scalable web applications, modern APIs and digital experiences while documenting everything I learn.',
  secretAdminCode: 'letmein',
  maintenanceMode: false,
  maintenanceMessage: 'We are making a few improvements and will be back shortly.',
  maintenanceTitle: 'We are building something sharper.',
  maintenanceExpectedReturn: 'Back online soon',
  maintenanceProgress: 72,
  maintenanceShowProgress: true,
  maintenanceAccent: 'violet',
  contactFormEnabled: true,
  heroBadge: 'Available for freelance work',
  heroHeadline: 'Software Developer. Freelancer. Content Creator.',
  heroSubheadline: 'I build scalable web applications, modern APIs and digital experiences — while documenting everything I learn along the way.',
  aboutIntro: [
    'I\u2019m Ankesh — a 3rd-year B.Tech CSE student who somewhere between operating systems assignments and HDL presentations started shipping real full-stack applications.',
    'That habit turned into two goals: freelancing as a software developer, and building a public audience around how the work actually gets done.',
    'I work fastest in the Next.js / Node.js / MongoDB world, but I don\u2019t stay in one lane — I reach for whatever stack the problem actually needs.',
  ],
  currentFocus: 'Advanced backend development (Node.js, Express, MongoDB), DSA for internship prep, and shipping freelance projects alongside coursework.',
  futureVision: 'Building a small studio around freelance dev work and a SaaS product of my own — with content as the distribution channel, not an afterthought.',
  timeline: [
    { year: '2023', title: 'Started B.Tech CSE', description: 'Began at Lovely Professional University, batch of 2028 — and started writing real code outside of coursework.', order: 1 },
    { year: '2024', title: 'First shipped projects', description: 'Built academic projects that ended up looking and working like production software.', order: 2 },
    { year: '2025', title: 'Went full-stack + AI', description: 'Started integrating LLM APIs into real products.', order: 3 },
    { year: 'Now', title: 'Freelancing + content', description: 'Taking on freelance projects while building a public audience around how the work gets done.', order: 4 },
  ],
  resumeDownloadUrl: '',
  resumeSummary: 'Full-Stack Developer & Content Creator',
  experience: [
    { role: 'Freelance Full-Stack Developer', period: '2025 — Present', description: 'Building full-stack apps and AI-powered tools for clients using Next.js, Node.js, and MongoDB.', order: 1 },
    { role: 'Independent Projects', period: '2023 — Present', description: 'Shipped 6+ projects spanning AI, systems visualization, and cultural storytelling websites.', order: 2 },
  ],
  education: [
    { school: 'Lovely Professional University', degree: 'B.Tech, Computer Science & Engineering', period: '2023 — 2027 (Batch 2028)', order: 1 },
  ],
  resumeSkills: ['Next.js', 'TypeScript', 'React', 'Node.js', 'Express', 'MongoDB', 'TailwindCSS', 'REST APIs', 'JWT', 'Git', 'DSA', 'Operating Systems'],
  platforms: [
    { name: 'YouTube', icon: 'Youtube', handle: '@ankeshbuilds', description: 'Full build breakdowns & tutorials', href: '#', order: 1 },
    { name: 'Instagram', icon: 'Instagram', handle: '@ankeshbuilds', description: 'Quick dev tips & reels', href: '#', order: 2 },
    { name: 'LinkedIn', icon: 'Linkedin', handle: 'Ankesh Kumar', description: 'Career + freelancing notes', href: '#', order: 3 },
    { name: 'Twitter / X', icon: 'Twitter', handle: '@ankeshbuilds', description: 'Build-in-public updates', href: '#', order: 4 },
  ],
  videos: [
    { title: 'Building an AI PDF Q&A app in Next.js', tag: 'Tutorial', thumbnail: '', href: '#', order: 1 },
    { title: 'JS Tip: Optional Chaining in 20 seconds', tag: 'Short', thumbnail: '', href: '#', order: 2 },
    { title: 'MongoDB vs SQL — how to actually choose', tag: 'Explainer', thumbnail: '', href: '#', order: 3 },
    { title: 'From student project to real product', tag: 'Story', thumbnail: '', href: '#', order: 4 },
  ],
  footerTagline: '',
  footerSocials: [
    { label: 'GitHub', href: 'https://github.com/thakurankeshkumar', icon: 'Github', order: 1 },
    { label: 'LinkedIn', href: '#', icon: 'Linkedin', order: 2 },
    { label: 'YouTube', href: '#', icon: 'Youtube', order: 3 },
    { label: 'Twitter', href: '#', icon: 'Twitter', order: 4 },
  ],
  footerCopyright: '',
  aboutPageTitle: 'From lecture halls to production deploys.',
  projectsPageTitle: 'Projects',
  projectsPageSubtitle: 'Real things I\u2019ve built — academic, freelance, and personal.',
  servicesPageTitle: 'What I can build for you',
  servicesPageSubtitle: 'Clear scope, clear timeline, clear price — no surprises halfway through.',
  blogPageTitle: 'Writing',
  blogPageSubtitle: 'Notes on building products, freelancing, and what I\u2019m learning.',
  contentPageTitle: 'I teach what I build',
  contentPageSubtitle: 'Short-form dev content and full build breakdowns, across every platform.',
  projectCategories: ['Web App', 'SaaS', 'API', 'Landing Page', 'Tool'],
};
